remote_theme: pages-themes/minimal@v0.2.0
title: Challenges and Differences of Management in Computer Science
description: A view on the different approaches to project management between industries. 
